// OrdresFabricationERP.jsx
import React, { useState, useEffect, useCallback } from "react";
import axios from "axios";
import { useTheme } from "../context/ThemeContext";
import { useLang } from "../context/LangContext";

const ERP_BASE_URL = "http://127.0.0.1:8001/api/erp/ordres-fabrication";

// ─── Traductions ────────────────────────────────────────────
const translations = {
  fr: {
    // Général
    loading: "Chargement...",
    saving: "Enregistrement...",
    error: "Erreur",
    success: "Succès",
    close: "Fermer",
    cancel: "Annuler",
    confirm: "Confirmer",
    delete: "Supprimer",
    edit: "Modifier",
    
    // Topbar
    appTitle: "ERP — Ordres de Fabrication",
    appSubtitle: "Gestion des OF",
    online: "En ligne",
    syncMES: "Sync MES",
    
    // KPIs
    totalOrders: "Total OFs",
    pending: "En attente",
    sentToMES: "Envoyés au MES",
    
    // Actions
    sendAll: "Envoyer tout",
    sending: "Envoi...",
    newOrder: "Nouvel OF",
    createOrder: "Créer un OF",
    editOrder: "Modifier l'OF",
    sendToMES: "Envoyer au MES",
    transmittedToMES: "Transmis au MES",
    
    // Form
    orderNumber: "N° OF",
    autoGenerated: "Auto-généré (séquentiel par jour)",
    product: "Produit",
    selectProduct: "Sélectionner...",
    quantity: "Quantité (kg)",
    startDate: "Date début",
    endDate: "Date fin",
    create: "Créer l'OF",
    update: "Mettre à jour",
    errorDateOrder: "La date de début doit être inférieure ou égale à la date de fin",
    
    // Products
    products: {
      "Ruban 100% coton": "Ruban 100% coton",
      "Ruban Polyester": "Ruban Polyester",
      "Ruban laine": "Ruban laine",
      "Ruban Acrylique": "Ruban Acrylique",
      "Ruban Soie": "Ruban Soie",
      "Ruban Lin": "Ruban Lin",
    },
    
    // Status
    status: "Statut",
    allStatus: "Tous statuts",
    pendingStatus: "En attente",
    sentStatus: "Envoyé",
    cancelledStatus: "Annulé",
    
    // Filters
    search: "Recherche",
    searchPlaceholder: "N° OF...",
    allProducts: "Tous les produits",
    
    // Table
    orderList: "Liste des ordres de fabrication",
    ordersDisplayed: "OF(s) affiché(s) sur",
    noOrders: "Aucun ordre de fabrication",
    createFirstOrder: "+ Créer un OF",
    colOrderNumber: "N° OF",
    colProduct: "Produit",
    colQuantity: "Qté (kg)",
    colStartDate: "Date début",
    colEndDate: "Date fin",
    colStatus: "Statut",
    colActions: "Actions",
    
    // Modal
    confirmDelete: "Confirmer la suppression",
    deleteConfirmMessage: "Voulez-vous supprimer l'OF",
    
    // Messages feedback
    errorLoading: "Erreur de chargement des OFs",
    fillRequiredFields: "Veuillez remplir tous les champs obligatoires",
    numberAlreadyExists: "Numéro déjà existant, nouveau numéro généré",
    orderUpdated: "OF mis à jour",
    orderCreated: "OF créé",
    orderSent: "OF envoyé au MES",
    ordersSent: "OF(s) envoyés",
    errorsOccurred: "erreur(s)",
    errorSending: "Erreur lors de l'envoi",
    errorSaving: "Erreur lors de la sauvegarde",
    errorBulkSend: "Erreur lors de l'envoi en masse",
    orderDeleted: "OF supprimé",
    errorDeletion: "Erreur de suppression",
  },
  en: {
    // General
    loading: "Loading...",
    saving: "Saving...",
    error: "Error",
    success: "Success",
    close: "Close",
    cancel: "Cancel",
    confirm: "Confirm",
    delete: "Delete",
    edit: "Edit",
    
    // Topbar
    appTitle: "ERP — Manufacturing Orders",
    appSubtitle: "MO Management and MES Interface",
    online: "Online",
    syncMES: "MES Sync",
    
    // KPIs
    totalOrders: "Total MOs",
    pending: "Pending",
    sentToMES: "Sent to MES",
    
    // Actions
    sendAll: "Send all",
    sending: "Sending...",
    newOrder: "New MO",
    createOrder: "Create MO",
    editOrder: "Edit MO",
    sendToMES: "Send to MES",
    transmittedToMES: "Transmitted to MES",
    
    // Form
    orderNumber: "MO #",
    autoGenerated: "Auto-generated (sequential per day)",
    product: "Product",
    selectProduct: "Select...",
    quantity: "Quantity (kg)",
    startDate: "Start date",
    endDate: "End date",
    create: "Create MO",
    update: "Update",
    errorDateOrder: "Start date must be before or equal to end date",
    
    // Products
    products: {
      "Ruban 100% coton": "100% Cotton Ribbon",
      "Ruban Polyester": "Polyester Ribbon",
      "Ruban laine": "Wool Ribbon",
      "Ruban Acrylique": "Acrylic Ribbon",
      "Ruban Soie": "Silk Ribbon",
      "Ruban Lin": "Linen Ribbon",
    },
    
    // Status
    status: "Status",
    allStatus: "All statuses",
    pendingStatus: "Pending",
    sentStatus: "Sent",
    cancelledStatus: "Cancelled",
    
    // Filters
    search: "Search",
    searchPlaceholder: "MO #...",
    allProducts: "All products",
    
    // Table
    orderList: "Manufacturing Orders List",
    ordersDisplayed: "MO(s) displayed out of",
    noOrders: "No manufacturing orders",
    createFirstOrder: "+ Create MO",
    colOrderNumber: "MO #",
    colProduct: "Product",
    colQuantity: "Qty (kg)",
    colStartDate: "Start date",
    colEndDate: "End date",
    colStatus: "Status",
    colActions: "Actions",
    
    // Modal
    confirmDelete: "Confirm deletion",
    deleteConfirmMessage: "Do you want to delete MO",
    
    // Messages feedback
    errorLoading: "Error loading MOs",
    fillRequiredFields: "Please fill all required fields",
    numberAlreadyExists: "Number already exists, new number generated",
    orderUpdated: "MO updated",
    orderCreated: "MO created",
    orderSent: "MO sent to MES",
    ordersSent: "MO(s) sent",
    errorsOccurred: "error(s)",
    errorSending: "Error sending",
    errorSaving: "Error saving",
    errorBulkSend: "Error during bulk send",
    orderDeleted: "MO deleted",
    errorDeletion: "Deletion error",
  },
};

// ─── Palette factory (dark / light) ────────────────────────
const makeC = (isDark) => ({
  bg: isDark ? "#0f172a" : "#f4f6f9",
  surface: isDark ? "#1e293b" : "#ffffff",
  border: isDark ? "#334155" : "#e3e8ef",
  accent: "#2563eb",
  accentLt: isDark ? "#1e3a5f" : "#eff4ff",
  green: "#16a34a",
  greenLt: isDark ? "#14532d" : "#f0fdf4",
  red: "#dc2626",
  redLt: isDark ? "#7f1d1d" : "#fef2f2",
  amber: "#d97706",
  amberLt: isDark ? "#78350f" : "#fffbeb",
  purple: "#7c3aed",
  purpleLt: isDark ? "#3b0764" : "#f5f3ff",
  text: isDark ? "#f1f5f9" : "#111827",
  sub: isDark ? "#cbd5e1" : "#374151",
  muted: isDark ? "#94a3b8" : "#6b7280",
  inputBg: isDark ? "#0f172a" : "#f9fafb",
  trOdd: isDark ? "#1e293b" : "#ffffff",
  trEven: isDark ? "#162032" : "#f4f6f9",
});

// ─── Style factory (dynamique avec le thème) ───────────────
const makeS = (C) => ({
  app: {
    fontFamily: "'IBM Plex Sans', 'Segoe UI', sans-serif",
    background: C.bg,
    minHeight: "100vh",
    color: C.text,
  },
  topbar: {
    background: C.surface,
    borderBottom: `1px solid ${C.border}`,
    padding: "0 2rem",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    height: 60,
    position: "sticky",
    top: 0,
    zIndex: 100,
    boxShadow: "0 1px 3px rgba(0,0,0,0.06)",
  },
  logoRow: { display: "flex", alignItems: "center", gap: "0.75rem" },
  logo: {
    width: 34, height: 34,
    background: C.accent,
    borderRadius: 8,
    display: "flex", alignItems: "center", justifyContent: "center",
    fontSize: "1rem", fontWeight: 700, color: "#fff",
    letterSpacing: "-0.03em",
  },
  h1: { margin: 0, fontSize: "1rem", fontWeight: 600, color: C.text, letterSpacing: "-0.01em" },
  h1sub: { margin: 0, fontSize: "0.75rem", color: C.muted },
  badgeOnline: {
    background: C.greenLt, color: C.green,
    border: `1px solid #bbf7d0`,
    borderRadius: 20, padding: "3px 10px",
    fontSize: "0.72rem", fontWeight: 600,
    display: "flex", alignItems: "center", gap: 4,
  },
  dot: { width: 6, height: 6, borderRadius: "50%", background: C.green, display: "inline-block" },
  badgeSync: {
    background: C.accentLt, color: C.accent,
    border: `1px solid #bfdbfe`,
    borderRadius: 20, padding: "3px 10px",
    fontSize: "0.72rem", fontWeight: 600,
  },

  main: { padding: "1.75rem 2rem", maxWidth: 1400, margin: "0 auto" },

  kpiRow: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "1rem",
    marginBottom: "1.75rem",
  },
  kpiCard: {
    background: C.surface,
    border: `1px solid ${C.border}`,
    borderRadius: 10,
    padding: "1.1rem 1.25rem",
    display: "flex", alignItems: "center", gap: "1rem",
    boxShadow: "0 1px 3px rgba(0,0,0,0.04)",
  },
  kpiIcon: (lt) => ({
    width: 40, height: 40, borderRadius: 8,
    background: lt,
    display: "flex", alignItems: "center", justifyContent: "center",
    fontSize: "1.15rem", flexShrink: 0,
  }),
  kpiLabel: { margin: "0 0 2px", fontSize: "0.72rem", color: C.muted, fontWeight: 500, letterSpacing: "0.03em" },
  kpiVal: (color) => ({ margin: 0, fontSize: "1.6rem", fontWeight: 700, color: color, lineHeight: 1 }),

  section: {
    background: C.surface,
    border: `1px solid ${C.border}`,
    borderRadius: 10,
    padding: "1.5rem",
    marginBottom: "1.25rem",
    boxShadow: "0 1px 3px rgba(0,0,0,0.04)",
  },
  sectionHeader: {
    display: "flex", justifyContent: "space-between",
    alignItems: "center", marginBottom: "1.25rem",
    paddingBottom: "0.75rem",
    borderBottom: `1px solid ${C.border}`,
  },
  sectionTitle: { margin: 0, fontSize: "0.9rem", fontWeight: 600, color: C.text },
  sectionSub: { margin: 0, fontSize: "0.78rem", color: C.muted },

  grid3: { display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "1rem" },
  fg: { display: "flex", flexDirection: "column", gap: "0.35rem" },
  label: { fontSize: "0.78rem", fontWeight: 500, color: C.sub },
  req: { color: C.red, marginLeft: 2 },
  input: {
    padding: "0.6rem 0.85rem",
    background: C.inputBg,
    border: `1px solid ${C.border}`,
    borderRadius: 7,
    color: C.text,
    fontSize: "0.875rem",
    fontFamily: "inherit",
    outline: "none",
    width: "100%",
    boxSizing: "border-box",
    transition: "border-color 0.15s, box-shadow 0.15s",
  },
  inputError: {
    padding: "0.6rem 0.85rem",
    background: C.inputBg,
    border: `1px solid ${C.red}`,
    borderRadius: 7,
    color: C.text,
    fontSize: "0.875rem",
    fontFamily: "inherit",
    outline: "none",
    width: "100%",
    boxSizing: "border-box",
  },
  select: {
    padding: "0.6rem 0.85rem",
    background: C.inputBg,
    border: `1px solid ${C.border}`,
    borderRadius: 7,
    color: C.text,
    fontSize: "0.875rem",
    fontFamily: "inherit",
    outline: "none",
    width: "100%",
    boxSizing: "border-box",
    cursor: "pointer",
  },

  btnRow: { display: "flex", gap: "0.75rem", marginTop: "1.25rem", paddingTop: "1rem", borderTop: `1px solid ${C.border}`, justifyContent: "flex-end" },
  btnPrimary: {
    background: C.accent, color: "#fff",
    border: "none", borderRadius: 7,
    padding: "0.6rem 1.5rem",
    fontFamily: "inherit", fontWeight: 600, fontSize: "0.875rem",
    cursor: "pointer", transition: "opacity .15s",
  },
  btnPrimaryDisabled: {
    background: C.muted, color: "#fff",
    border: "none", borderRadius: 7,
    padding: "0.6rem 1.5rem",
    fontFamily: "inherit", fontWeight: 600, fontSize: "0.875rem",
    cursor: "not-allowed",
    opacity: 0.6,
  },
  btnDanger: {
    background: C.redLt, color: C.red,
    border: `1px solid #fecaca`,
    borderRadius: 7, padding: "0.5rem 0.85rem",
    fontFamily: "inherit", fontWeight: 500, fontSize: "0.8rem",
    cursor: "pointer",
  },
  btnGhost: {
    background: C.inputBg, color: C.sub,
    border: `1px solid ${C.border}`,
    borderRadius: 7, padding: "0.5rem 0.85rem",
    fontFamily: "inherit", fontWeight: 500, fontSize: "0.8rem",
    cursor: "pointer",
  },
  btnSecondary: {
    background: C.green, color: "#fff",
    border: "none",
    borderRadius: 7, padding: "0.6rem 1.25rem",
    fontFamily: "inherit", fontWeight: 500, fontSize: "0.875rem",
    cursor: "pointer",
  },

  table: { width: "100%", borderCollapse: "collapse", fontSize: "0.875rem" },
  thead: { background: C.bg },
  th: {
    textAlign: "left", padding: "0.6rem 0.9rem",
    borderBottom: `1px solid ${C.border}`,
    color: C.muted, fontWeight: 600, fontSize: "0.72rem",
    letterSpacing: "0.05em", textTransform: "uppercase",
  },
  tr: (i) => ({
    background: i % 2 === 0 ? C.trOdd : C.trEven,
  }),
  td: { padding: "0.7rem 0.9rem", borderBottom: `1px solid ${C.border}`, color: C.sub, verticalAlign: "middle" },

  pill: (bg, color, border) => ({
    display: "inline-flex", alignItems: "center",
    padding: "2px 9px", borderRadius: 20,
    fontSize: "0.72rem", fontWeight: 600,
    background: bg, color: color,
    border: `1px solid ${border}`,
  }),

  alertBox: (bg, border, color) => ({
    background: bg,
    border: `1px solid ${border}`,
    borderLeft: `3px solid ${color}`,
    borderRadius: 8,
    padding: "0.75rem 1rem",
    marginBottom: "1rem",
    fontSize: "0.85rem",
    color: color,
    display: "flex", alignItems: "flex-start", gap: "0.5rem",
  }),
  emptyState: {
    textAlign: "center", padding: "3rem",
    color: C.muted,
    display: "flex", flexDirection: "column", alignItems: "center", gap: "0.5rem",
  },
  emptyIcon: { fontSize: "2.5rem" },
  filterRow: {
    display: "flex", gap: "0.75rem",
    marginBottom: "1.25rem", flexWrap: "wrap",
    alignItems: "flex-end",
  },
  filterGroup: { flex: 1, minWidth: "180px" },
  modalOverlay: {
    position: "fixed", top: 0, left: 0, right: 0, bottom: 0,
    background: "rgba(0,0,0,0.5)",
    display: "flex", alignItems: "center", justifyContent: "center",
    zIndex: 1000,
  },
  modal: {
    background: C.surface,
    borderRadius: 12,
    padding: "1.5rem",
    maxWidth: 450,
    width: "90%",
    boxShadow: "0 20px 40px rgba(0,0,0,0.2)",
  },
  modalActions: { display: "flex", gap: "0.75rem", justifyContent: "flex-end", marginTop: "1.5rem" },
  errorText: { color: C.red, fontSize: "0.7rem", marginTop: "0.25rem" },
});

const PRODUITS = [
  "Ruban 100% coton",
  "Ruban Polyester",
  "Ruban laine",
  "Ruban Acrylique",
  "Ruban Soie",
  "Ruban Lin",
];

// ✅ Fonction pour transformer le statut de l'API vers l'affichage
const getDisplayStatut = (apiStatut) => {
  if (apiStatut === "Brouillon") return "pending";
  if (apiStatut === "Envoyé") return "sent";
  if (apiStatut === "Annulé") return "cancelled";
  return "pending";
};

// ✅ Fonction pour obtenir le libellé affiché du statut
const getStatutLabel = (displayStatut, t) => {
  const labels = {
    pending: t.pendingStatus,
    sent: t.sentStatus,
    cancelled: t.cancelledStatus,
  };
  return labels[displayStatut] || t.pendingStatus;
};

// ✅ Couleurs basées sur le statut d'affichage (dynamique avec thème)
const getStatutColor = (displayStatut, C) => {
  const colors = {
    pending: { bg: C.amberLt, text: C.amber },
    sent: { bg: C.greenLt, text: C.green },
    cancelled: { bg: C.redLt, text: C.red },
  };
  return colors[displayStatut] || colors.pending;
};

// ✅ Icônes basées sur le statut d'affichage
const statutIcon = { pending: "⏳", sent: "✅", cancelled: "❌" };

// Génération du numéro séquentiel
const generateSequentialNumero = (existingOFs) => {
  const today = new Date();
  const yy = String(today.getFullYear()).slice(2);
  const mm = String(today.getMonth() + 1).padStart(2, "0");
  const dd = String(today.getDate()).padStart(2, "0");
  const prefix = `OF-${yy}${mm}${dd}`;

  const todayOFs = existingOFs.filter(of => of.numero && of.numero.startsWith(prefix));
  const existingNumbers = todayOFs
    .map(of => {
      const match = of.numero.match(/OF-\d{6}-(\d{3})$/);
      return match ? parseInt(match[1], 10) : 0;
    })
    .filter(num => num > 0);

  let nextNumber = 1;
  if (existingNumbers.length > 0) {
    const maxNumber = Math.max(...existingNumbers);
    nextNumber = maxNumber + 1;
  }

  if (nextNumber > 999) {
    for (let i = 1; i <= 999; i++) {
      if (!existingNumbers.includes(i)) {
        nextNumber = i;
        break;
      }
    }
  }

  return `${prefix}-${String(nextNumber).padStart(3, "0")}`;
};

const fmt = (n) => Number(n || 0).toLocaleString("fr-FR");

const OrdresFabricationERP = () => {
  const { isDark } = useTheme();
  const { lang } = useLang();
  const t = translations[lang] || translations.fr;

  const C = makeC(isDark);
  const s = makeS(C);

  const [ofs, setOfs] = useState([]);
  const [loading, setLoading] = useState(false);
  const [sendingId, setSendingId] = useState(null);
  const [msg, setMsg] = useState({ text: "", type: "" });
  const [showForm, setShowForm] = useState(false);
  const [editOf, setEditOf] = useState(null);
  const [filterProduit, setFilterProduit] = useState("");
  const [filterStatut, setFilterStatut] = useState("");
  const [searchOF, setSearchOF] = useState("");
  const [confirmDelete, setConfirmDelete] = useState(null);
  const [dateError, setDateError] = useState("");

  const [form, setForm] = useState({
    numero: "",
    produit: "",
    quantite: "",
    date_debut: "",
    date_fin: "",
  });

  // ✅ Validation des dates
  const validateDates = (dateDebut, dateFin) => {
    if (dateDebut && dateFin) {
      if (new Date(dateDebut) > new Date(dateFin)) {
        setDateError(t.errorDateOrder);
        return false;
      }
    }
    setDateError("");
    return true;
  };

  // ✅ Quand la date de début change
  const handleDateDebutChange = (e) => {
    const newDateDebut = e.target.value;
    setForm({ ...form, date_debut: newDateDebut });
    validateDates(newDateDebut, form.date_fin);
  };

  // ✅ Quand la date de fin change
  const handleDateFinChange = (e) => {
    const newDateFin = e.target.value;
    setForm({ ...form, date_fin: newDateFin });
    validateDates(form.date_debut, newDateFin);
  };

  const showMsg = (text, type = "success") => {
    setMsg({ text, type });
    setTimeout(() => setMsg({ text: "", type: "" }), 4000);
  };

  const fetchOFs = useCallback(async () => {
    setLoading(true);
    try {
      const res = await axios.get(ERP_BASE_URL + "/");
      setOfs(res.data);
    } catch {
      showMsg(t.errorLoading, "error");
    } finally {
      setLoading(false);
    }
  }, [t]);

  useEffect(() => {
    fetchOFs();
  }, [fetchOFs]);

  useEffect(() => {
    if (showForm && !editOf) {
      const newNumero = generateSequentialNumero(ofs);
      setForm(prev => ({ 
        ...prev, 
        numero: newNumero,
        date_debut: "",
        date_fin: ""
      }));
    }
  }, [showForm, editOf, ofs]);

  const handleSubmit = async () => {
    if (!form.produit || !form.quantite) {
      showMsg(t.fillRequiredFields, "error");
      return;
    }

    // ✅ Vérifier la validité des dates
    if (!validateDates(form.date_debut, form.date_fin)) {
      showMsg(t.errorDateOrder, "error");
      return;
    }

    if (!editOf) {
      const existingOF = ofs.find(of => of.numero === form.numero);
      if (existingOF) {
        const newNumero = generateSequentialNumero(ofs);
        setForm(prev => ({ ...prev, numero: newNumero }));
        showMsg(t.numberAlreadyExists, "error");
        return;
      }
    }

    try {
      const payload = {
        numero: form.numero,
        produit: form.produit,
        quantite: parseInt(form.quantite),
        date_debut: form.date_debut || null,
        date_fin: form.date_fin || null,
      };

      if (editOf) {
        await axios.put(`${ERP_BASE_URL}/${editOf.id}`, payload);
        showMsg(`${t.orderUpdated} ${form.numero}`);
      } else {
        await axios.post(ERP_BASE_URL + "/", payload);
        showMsg(`${t.orderCreated} ${form.numero}`);
      }

      setShowForm(false);
      setEditOf(null);
      resetForm();
      fetchOFs();
    } catch (err) {
      const msg = err.response?.data?.detail || t.errorSaving;
      showMsg(msg, "error");
    }
  };

  const handleEnvoyer = async (of) => {
    setSendingId(of.id);
    try {
      await axios.post(`${ERP_BASE_URL}/${of.id}/envoyer-mes`);
      showMsg(`${t.orderSent} ${of.numero}`);
      fetchOFs();
    } catch (err) {
      const msg = err.response?.data?.detail || t.errorSending;
      showMsg(msg, "error");
    } finally {
      setSendingId(null);
    }
  };

  const handleEnvoyerTous = async () => {
    setSendingId("all");
    try {
      const res = await axios.post(`${ERP_BASE_URL}/envoyer-tous-mes`);
      showMsg(`${res.data.envoyes} ${t.ordersSent}${res.data.erreurs > 0 ? `, ${res.data.erreurs} ${t.errorsOccurred}` : ""}`);
      fetchOFs();
    } catch {
      showMsg(t.errorBulkSend, "error");
    } finally {
      setSendingId(null);
    }
  };

  const handleDelete = async (of) => {
    try {
      await axios.delete(`${ERP_BASE_URL}/${of.id}`);
      showMsg(`${t.orderDeleted} ${of.numero}`);
      setConfirmDelete(null);
      fetchOFs();
    } catch (err) {
      showMsg(err.response?.data?.detail || t.errorDeletion, "error");
    }
  };

  const openEdit = (of) => {
    setEditOf(of);
    setForm({
      numero: of.numero,
      produit: of.produit,
      quantite: String(of.quantite),
      date_debut: of.date_debut || "",
      date_fin: of.date_fin || "",
    });
    setDateError("");
    setShowForm(true);
  };

  const resetForm = () => {
    const newNumero = generateSequentialNumero(ofs);
    setForm({
      numero: newNumero,
      produit: "",
      quantite: "",
      date_debut: "",
      date_fin: "",
    });
    setDateError("");
  };

  const cancelForm = () => {
    setShowForm(false);
    setEditOf(null);
    resetForm();
  };

  // ✅ Vérifier si le formulaire est valide
  const isFormValid = () => {
    if (!form.produit || !form.quantite) return false;
    if (dateError) return false;
    return true;
  };

  // ✅ Filtrage avec transformation du statut
  const filtered = ofs.filter((o) => {
    const matchProduit = !filterProduit || o.produit === filterProduit;
    const displayStatut = getDisplayStatut(o.statut_erp);
    const matchStatut = !filterStatut || displayStatut === filterStatut;
    const matchSearch = !searchOF || o.numero.toLowerCase().includes(searchOF.toLowerCase());
    return matchProduit && matchStatut && matchSearch;
  });

  // ✅ Compteurs avec transformation
  const totalEnAttente = ofs.filter(o => getDisplayStatut(o.statut_erp) === "pending").length;
  const totalEnvoye = ofs.filter(o => getDisplayStatut(o.statut_erp) === "sent").length;

  return (
    <div style={s.app}>
      {/* TOPBAR */}
      <div style={s.topbar}>
        <div style={s.logoRow}>
          <div style={s.logo}>E</div>
          <div>
            <p style={s.h1}>{t.appTitle}</p>
            <p style={s.h1sub}>{t.appSubtitle}</p>
          </div>
        </div>
        <div style={{ display: "flex", gap: "0.5rem", alignItems: "center" }}>
          <span style={s.badgeOnline}><span style={s.dot} />{t.online}</span>
          <span style={s.badgeSync}>{t.syncMES}</span>
        </div>
      </div>

      <div style={s.main}>
        {/* MESSAGES */}
        {msg.text && (
          <div style={s.alertBox(
            msg.type === "error" ? C.redLt : C.greenLt,
            msg.type === "error" ? "#fecaca" : "#bbf7d0",
            msg.type === "error" ? C.red : C.green
          )}>
            {msg.type === "error" ? "⚠️" : "✅"} {msg.text}
          </div>
        )}

        {/* KPI ROW */}
        <div style={s.kpiRow}>
          {[
            { label: t.totalOrders, val: ofs.length, icon: "📊", color: C.accent, lt: C.accentLt },
            { label: t.pending, val: totalEnAttente, icon: "⏳", color: C.amber, lt: C.amberLt },
            { label: t.sentToMES, val: totalEnvoye, icon: "✅", color: C.green, lt: C.greenLt },
          ].map((k, idx) => (
            <div key={idx} style={s.kpiCard}>
              <div style={s.kpiIcon(k.lt)}>{k.icon}</div>
              <div>
                <p style={s.kpiLabel}>{k.label}</p>
                <p style={s.kpiVal(k.color)}>{k.val}</p>
              </div>
            </div>
          ))}
        </div>

        {/* ACTIONS BAR */}
        <div style={{ ...s.section, padding: "1rem 1.5rem", marginBottom: "1.25rem" }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: "1rem" }}>
            <div style={{ display: "flex", gap: "0.75rem" }}>
              {totalEnAttente > 0 && (
                <button style={s.btnSecondary} onClick={handleEnvoyerTous} disabled={sendingId === "all"}>
                  {sendingId === "all" ? t.sending : `🚀 ${t.sendAll} (${totalEnAttente})`}
                </button>
              )}
              <button style={s.btnPrimary} onClick={() => { setEditOf(null); resetForm(); setShowForm(true); }}>
                + {t.newOrder}
              </button>
            </div>
          </div>
        </div>

        {/* FORMULAIRE */}
        {showForm && (
          <div style={{ ...s.section, border: `2px solid ${C.accent}` }}>
            <div style={s.sectionHeader}>
              <div>
                <p style={s.sectionTitle}>{editOf ? t.editOrder : t.createOrder}</p>
                <p style={s.sectionSub}>{t.autoGenerated}</p>
              </div>
              <button style={s.btnGhost} onClick={cancelForm}>✕ {t.cancel}</button>
            </div>

            <div style={s.grid3}>
              <div style={s.fg}>
                <label style={s.label}>{t.orderNumber} <span style={s.req}>*</span></label>
                <input
                  style={{ ...s.input, background: editOf ? C.inputBg : C.accentLt, fontFamily: "monospace", fontWeight: 600 }}
                  value={form.numero}
                  onChange={(e) => setForm({ ...form, numero: e.target.value })}
                  placeholder="OF-YYMMDD-XXX"
                  readOnly={!editOf}
                />
                {!editOf && <small style={{ fontSize: "0.7rem", color: C.muted }}>{t.autoGenerated}</small>}
              </div>

              <div style={s.fg}>
                <label style={s.label}>{t.product} <span style={s.req}>*</span></label>
                <select style={s.select} value={form.produit} onChange={e => setForm({ ...form, produit: e.target.value })}>
                  <option value="">{t.selectProduct}</option>
                  {PRODUITS.map(p => <option key={p} value={p}>{t.products[p] || p}</option>)}
                </select>
              </div>

              <div style={s.fg}>
                <label style={s.label}>{t.quantity} <span style={s.req}>*</span></label>
                <input style={s.input} type="number" min="1" value={form.quantite} onChange={e => setForm({ ...form, quantite: e.target.value })} placeholder="Ex: 500" />
              </div>

              <div style={s.fg}>
                <label style={s.label}>{t.startDate}</label>
                <input 
                  style={dateError ? s.inputError : s.input} 
                  type="date" 
                  value={form.date_debut} 
                  onChange={handleDateDebutChange}
                />
              </div>

              <div style={s.fg}>
                <label style={s.label}>{t.endDate}</label>
                <input 
                  style={dateError ? s.inputError : s.input} 
                  type="date" 
                  value={form.date_fin} 
                  onChange={handleDateFinChange}
                />
              </div>
            </div>

            {/* Affichage de l'erreur de date */}
            {dateError && (
              <div style={s.errorText}>
                ⚠️ {dateError}
              </div>
            )}

            <div style={s.btnRow}>
              <button type="button" style={s.btnGhost} onClick={cancelForm}>{t.cancel}</button>
              <button 
                style={isFormValid() ? s.btnPrimary : s.btnPrimaryDisabled} 
                onClick={handleSubmit}
                disabled={!isFormValid()}
              >
                {editOf ? t.update : t.create}
              </button>
            </div>
          </div>
        )}

        {/* FILTRES & TABLEAU */}
        <div style={s.section}>
          <div style={s.sectionHeader}>
            <div>
              <p style={s.sectionTitle}>{t.orderList}</p>
              <p style={s.sectionSub}>{filtered.length} {t.ordersDisplayed} {ofs.length}</p>
            </div>
          </div>

          <div style={s.filterRow}>
            <div style={s.filterGroup}>
              <label style={s.label}>🔍 {t.search}</label>
              <input style={s.input} placeholder={t.searchPlaceholder} value={searchOF} onChange={e => setSearchOF(e.target.value)} />
            </div>
            <div style={s.filterGroup}>
              <label style={s.label}>{t.product}</label>
              <select style={s.select} value={filterProduit} onChange={e => setFilterProduit(e.target.value)}>
                <option value="">{t.allProducts}</option>
                {PRODUITS.map(p => <option key={p} value={p}>{t.products[p] || p}</option>)}
              </select>
            </div>
            <div style={s.filterGroup}>
              <label style={s.label}>{t.status}</label>
              <select style={s.select} value={filterStatut} onChange={e => setFilterStatut(e.target.value)}>
                <option value="">{t.allStatus}</option>
                <option value="pending">⏳ {t.pendingStatus}</option>
                <option value="sent">✅ {t.sentStatus}</option>
                <option value="cancelled">❌ {t.cancelledStatus}</option>
              </select>
            </div>
          </div>

          {loading ? (
            <div style={s.emptyState}>
              <div style={s.emptyIcon}>⏳</div>
              <p>{t.loading}</p>
            </div>
          ) : filtered.length === 0 ? (
            <div style={s.emptyState}>
              <div style={s.emptyIcon}>📭</div>
              <p>{t.noOrders}</p>
              <button style={s.btnPrimary} onClick={() => setShowForm(true)}>{t.createFirstOrder}</button>
            </div>
          ) : (
            <div style={{ overflowX: "auto" }}>
              <table style={s.table}>
                <thead style={s.thead}>
                  <tr>
                    {[t.colOrderNumber, t.colProduct, t.colQuantity, t.colStartDate, t.colEndDate, t.colStatus, t.colActions].map(h => (
                      <th key={h} style={s.th}>{h}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {filtered.map((of, i) => {
                    // ✅ Transformation du statut pour l'affichage
                    const displayStatut = getDisplayStatut(of.statut_erp);
                    const statutLabel = getStatutLabel(displayStatut, t);
                    const sc = getStatutColor(displayStatut, C);
                    return (
                      <tr key={of.id} style={s.tr(i)}>
                        <td style={s.td}>
                          <code style={{ background: C.accentLt, padding: "2px 8px", borderRadius: 4, fontSize: "0.8rem", fontFamily: "monospace", color: C.accent }}>
                            {of.numero}
                          </code>
                        </td>
                        <td style={s.td}>{t.products[of.produit] || of.produit}</td>
                        <td style={s.td}><strong>{fmt(of.quantite)} kg</strong></td>
                        <td style={s.td}>{of.date_debut || "—"}</td>
                        <td style={s.td}>{of.date_fin || "—"}</td>
                        <td style={s.td}>
                          <span style={s.pill(sc.bg, sc.text, "transparent")}>
                            {statutIcon[displayStatut]} {statutLabel}
                          </span>
                        </td>
                        <td style={s.td}>
                          <div style={{ display: "flex", gap: "0.5rem", flexWrap: "wrap" }}>
                            {displayStatut === "pending" && (
                              <>
                                <button style={s.btnGhost} onClick={() => openEdit(of)} title={t.edit}>✏️</button>
                                <button
                                  style={{ ...s.btnSecondary, padding: "0.4rem 0.85rem" }}
                                  onClick={() => handleEnvoyer(of)}
                                  disabled={sendingId === of.id}
                                  title={t.sendToMES}
                                >
                                  {sendingId === of.id ? "⏳" : "🚀"}
                                </button>
                                <button
                                  style={{ ...s.btnDanger }}
                                  onClick={() => setConfirmDelete(of)}
                                  title={t.delete}
                                >
                                  🗑
                                </button>
                              </>
                            )}
                            {displayStatut === "sent" && (
                              <span style={{ color: C.green, fontSize: "0.8rem", fontWeight: 500 }}>✓ {t.transmittedToMES}</span>
                            )}
                          </div>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </div>

      {/* MODAL CONFIRMATION */}
      {confirmDelete && (
        <div style={s.modalOverlay} onClick={() => setConfirmDelete(null)}>
          <div style={s.modal} onClick={(e) => e.stopPropagation()}>
            <h3 style={{ margin: "0 0 0.5rem", color: C.text }}>{t.confirmDelete}</h3>
            <p style={{ color: C.sub, marginBottom: "1.5rem" }}>
              {t.deleteConfirmMessage} <strong>{confirmDelete.numero}</strong> ?
            </p>
            <div style={s.modalActions}>
              <button style={s.btnGhost} onClick={() => setConfirmDelete(null)}>{t.cancel}</button>
              <button style={{ ...s.btnDanger, padding: "0.6rem 1.25rem" }} onClick={() => handleDelete(confirmDelete)}>
                {t.delete}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default OrdresFabricationERP;